services:
  backend:
    image: hoainam213/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://tranhoainamhtkg:Hoainam213@mern-demo.38tx5z4.mongodb.net/?appName=mern-demo"

  frontend:
    image: hoainam213/mern-frontend:1.0
    ports:
      - "5173:5173"