services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://tranhoainamhtkg:Hoainam213@mern-demo.38tx5z4.mongodb.net/?appName=mern-demo"

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"